output: testing/outputs/single_json_output.json
custom_transform: SingleJsonRetriever

file_groups:
    issue_1:
        [
            "testing/resources/browsertime.json",
            "testing/resources/browsertime_copy.json",
        ]
